### ISSUE TITLE
Runners are not being re-used

### ISSUE THREAD

**Issue by NiklasRosenstein** [testflows/TestFlows-GitHub-Hetzner-Runners#14]
Hello! Thanks again for this nice tool.

I have pretty standard installation of the application (i.e. not many overwritten config options, besides the startup script and default image, as well as increasing the time to cleanup powered off servers). I kicked off a bunch of CI jobs on my repository earlier through commits, now it seems it has accumulated 10 powered off servers (which seems to be the default max) and it doesn't progress.

I.e. it doesn't spin up new ones (which makes sense as per the default worker limit) but also doesn't reuse the powered off runners.

These are the config values I override:

```yaml
    image: ghcr.io/kraken-build/github-runners:${tag}
    command:
      - --startup-x64-script=/opt/startup-x64.sh
      - --startup-arm64-script=/opt/startup-arm64.sh
      - --max-unused-runner-time=3000  # 50 minutes
      - --max-powered-off-time=3000  # 50 minutes
      # NOTE: We can not set a default image per architecture, so this will be invalid for arm servers.
      #       See https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/issues/10
      - --default-image=x86:app:docker-ce
    environment:
      - GITHUB_TOKEN=${github_token}
      - GITHUB_REPOSITORY=${repo.name}
      - HETZNER_TOKEN=${repo.hetzner_token}
    volumes:
      - ./startup-x64.sh:/opt/startup-x64.sh:ro
      - ./startup-arm64.sh:/opt/startup-arm64.sh:ro
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
    restart: always
```

Aside from this it's very vanilla, see the Dockerfile:

```Dockerfile
FROM python:3.10 as builder

RUN pip install --upgrade pip && \
    # See https://github.com/yaml/pyyaml/issues/736
    echo 'Cython < 3.0' > /tmp/constraint.txt && \
    pip install pex && \
    PIP_CONSTRAINT=/tmp/constraint.txt pex testflows.github.hetzner.runners==1.5.231020.1122452 \
        -c github-hetzner-runners -o /usr/local/bin/github-hetzner-runners

FROM python:3.10
COPY --from=builder /usr/local/bin/github-hetzner-runners /usr/local/bin/github-hetzner-runners
ENTRYPOINT [ "/usr/local/bin/github-hetzner-runners" ]
```

Screenshot of a currently pending job: 

<img width="1141" alt="image" src="https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/assets/1318438/7680ef14-d0bc-4f00-8bb0-452dc4ee5bd8">

Maybe relevant screenshot from two of the VMs that I think should get reused:

<img width="1485" alt="image" src="https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/assets/1318438/82a9eda0-f11e-435c-8505-f13c70370437">

<img width="1463" alt="image" src="https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/assets/1318438/8b266aac-b8ac-46ed-a44c-64ca1e974056">

There's been no changes to the hetzner-runners configuration in the last week.
