### ISSUE TITLE
argument -c/--config: name 'deploy' is not defined

### ISSUE THREAD

**Issue by JulianGro** [testflows/TestFlows-GitHub-Hetzner-Runners#25]
Was there a breaking change?
The newest update doesn't seem to work with my config file anymore:
```
root@Hetzner-Runner-Scaler:~# github-hetzner-runners -c config.yaml cloud redeploy
usage: github-hetzner-runners [-h] [-v] [--license] [-c yaml] [--github-token token] [--github-repository name] [--hetzner-token token] [--ssh-key path] [-m count] [-r on|off] [--end-of-life minutes] [--delete-random]
                              [--max-runners-in-workflow-run count] [--with-label label --with-label ...] [--label-prefix prefix] [--meta-label name label,... --meta-label name label,... --meta-label]
                              [--default-image architecture:type:name_or_description] [--default-type name] [--default-location name] [-w count] [--scripts path] [--max-powered-off-time sec] [--max-unused-runner-time sec]
                              [--max-runner-registration-time sec] [--max-server-ready-time sec] [--scale-up-interval sec] [--scale-down-interval sec] [--debug] [--service-mode] [--embedded-mode]
                              command ...
github-hetzner-runners: error: argument -c/--config: name 'deploy' is not defined
root@Hetzner-Runner-Scaler:~# 
```
Here is my config file:
```
root@Hetzner-Runner-Scaler:~# cat config.yaml 
config:
    github_token: REDACTED
    github_repository: overte-org/overte
    hetzner_token: REDACTED
    ssh_key: "~/.ssh/id_rsa.pub"
    max_runners: 30
    recycle: true
    with_label:
      - "self_hosted"
    default_image: "x86:system:ubuntu-22.04"
    default_server_type: cx22
    # Server for deploying Runners
    cloud:
        server_name: "GitHub-Runner-Deployer"
        deploy:
            server_type: cx22
            image: "x86:system:ubuntu-22.04"
            #location:
            #setup_script:


root@Hetzner-Runner-Scaler:~#
```
Replacing `deploy:` with `deploy_:` doesn't fix the issue.
I have redeployed multiple times on version 1.7.240516.1143322 without issue on the same config file.
