### ISSUE TITLE
Standby runners do not maintain the count

### ISSUE THREAD

**Issue by MyroTk** [testflows/TestFlows-GitHub-Hetzner-Runners#33]
I have 5 standby runners specified in my config, but when running the service, only 2-3 are online in `/settings/actions/runners` of the Github project.

Config for the standby runner component:
```
    standby_runners:
       - labels:
          - self-hosted
          - on-demand
          - type-cax11
          - image-arm-snapshot-22.04-arm
          - startup-snapshot
          - setup-none
         count: 5
         replenish_immediately: true
```
