### ISSUE TITLE
Add support for local caching volumes to speed up CI/CD jobs

### ISSUE THREAD

**Issue by vzakaznikov** [testflows/TestFlows-GitHub-Hetzner-Runners#65]
We need to add support for local caching volumes to speed up CI/CD jobs.

This would allow a job to run on a runner that has access to a pre-attached volume, improving performance for tasks that benefit from persistent data between runs.

Example usage:

```yaml
jobs:
  my-job:
    runs-on: [type-cpx21 volume-<volume_name>]
```
