### ISSUE TITLE
runs picked up by hetzner runners even if `runs-on:` does not include `self-hosted`

### ISSUE THREAD

**Issue by almostintuitive** [testflows/TestFlows-GitHub-Hetzner-Runners#8]
In the same repo where we subscribe to hetzner's self hosted runners, we also use buildjet AND standard github runners, but around 50% of the time, the hetzner runners are picking up these jobs even if:
`runs-on: ubuntu-latest` is specified.
Can you help us debug / resolve this?
Thank you!

**Comment by almostintuitive** [comment]
an example workflow that's being picked up by hetzner runners around 20% of the time:
```
name: Black

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          version: "~= 22.12"
```
